######################################################################
# Automatically generated by qmake (2.01a) Fri 17. Dec 12:52:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += declarative
